sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
after_script: cd ~
# deploy:
#   provider: pypi
#   user: "YOURUSERNAME"
#   password:
#     secure: "YOURPASSWORD"